config/routes.rb
Dreamdash::Application.routes.draw do
  resources :dashboards do
  	put :change, :on => :member
  end
  
  resources :charts do
    collection do
      get :test_draggable
    end
  end
  
  resources :datasources
  

  resources :pages do
  	put :table1, :on => :member
  	put :xaxis1, :on => :member
  	put :yaxis1, :on => :member
  end
  
  devise_for :users

  match "dashboard" => "pages#test"
  match "layers" => "pages#layers"  
  match "new_chart" => "pages#createcharts"

  root :to => "pages#home"
end

app/models/datasource.rb
class Datasource < ActiveRecord::Base
end

app/controllers/datasources_controller.rb
class DatasourcesController < ApplicationController
  # GET /datasources
  # GET /datasources.xml
  def index
    @datasources = Datasource.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @datasources }
    end
  end

  # GET /datasources/1
  # GET /datasources/1.xml
  def show
    @datasource = Datasource.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @datasource }
    end
  end

  # GET /datasources/new
  # GET /datasources/new.xml
  def new
    @datasource = Datasource.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @datasource }
    end
  end

  # GET /datasources/1/edit
  def edit
    @datasource = Datasource.find(params[:id])
  end

  # POST /datasources
  # POST /datasources.xml
  def create
    @datasource = Datasource.new(params[:datasource])

    respond_to do |format|
      if @datasource.save
        format.html { redirect_to(@datasource, :notice => 'Datasource was successfully created.') }
        format.xml  { render :xml => @datasource, :status => :created, :location => @datasource }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @datasource.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /datasources/1
  # PUT /datasources/1.xml
  def update
    @datasource = Datasource.find(params[:id])

    respond_to do |format|
      if @datasource.update_attributes(params[:datasource])
        format.html { redirect_to(@datasource, :notice => 'Datasource was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @datasource.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /datasources/1
  # DELETE /datasources/1.xml
  def destroy
    @datasource = Datasource.find(params[:id])
    @datasource.destroy

    respond_to do |format|
      format.html { redirect_to(datasources_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/datasources_helper.rb
module DatasourcesHelper
end

app/views/datasources/_form.html.erb
<%= form_for(@datasource) do |f| %>
  <% if @datasource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@datasource.errors.count, "error") %> prohibited this datasource from being saved:</h2>

      <ul>
      <% @datasource.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :database %><br />
    <%= f.text_field :database %>
  </div>
  <div class="field">
    <%= f.label :host %><br />
    <%= f.text_field :host %>
  </div>
  <div class="field">
    <%= f.label :database_name %><br />
    <%= f.text_field :database_name %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :database_port %><br />
    <%= f.text_field :database_port %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/datasources/edit.html.erb
<h1>Editing datasource</h1>

<%= render 'form' %>

<%= link_to 'Show', @datasource %> |
<%= link_to 'Back', datasources_path %>

app/views/datasources/index.html.erb
<h1>Listing datasources</h1>

<table>
  <tr>
    <th>User</th>
    <th>Database</th>
    <th>Host</th>
    <th>Database name</th>
    <th>User</th>
    <th>Password</th>
    <th>Database port</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @datasources.each do |datasource| %>
  <tr>
    <td><%= datasource.user_id %></td>
    <td><%= datasource.database %></td>
    <td><%= datasource.host %></td>
    <td><%= datasource.database_name %></td>
    <td><%= datasource.user %></td>
    <td><%= datasource.password %></td>
    <td><%= datasource.database_port %></td>
    <td><%= link_to 'Show', datasource %></td>
    <td><%= link_to 'Edit', edit_datasource_path(datasource) %></td>
    <td><%= link_to 'Destroy', datasource, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Datasource', new_datasource_path %>

app/views/datasources/new.html.erb
<h1>New datasource</h1>

<%= render 'form' %>

<%= link_to 'Back', datasources_path %>

app/views/datasources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @datasource.user_id %>
</p>

<p>
  <b>Database:</b>
  <%= @datasource.database %>
</p>

<p>
  <b>Host:</b>
  <%= @datasource.host %>
</p>

<p>
  <b>Database name:</b>
  <%= @datasource.database_name %>
</p>

<p>
  <b>User:</b>
  <%= @datasource.user %>
</p>

<p>
  <b>Password:</b>
  <%= @datasource.password %>
</p>

<p>
  <b>Database port:</b>
  <%= @datasource.database_port %>
</p>


<%= link_to 'Edit', edit_datasource_path(@datasource) %> |
<%= link_to 'Back', datasources_path %>