config/routes.rb
Dreamdash::Application.routes.draw do
  resources :dashboards do
  	put :change, :on => :member
  end
  
  resources :charts do
    collection do
      get :test_draggable
    end
  end
  
  resources :datasources
  

  resources :pages do
  	put :table1, :on => :member
  	put :xaxis1, :on => :member
  	put :yaxis1, :on => :member
  end
  
  devise_for :users

  match "dashboard" => "pages#test"
  match "layers" => "pages#layers"  
  match "new_chart" => "pages#createcharts"

  root :to => "pages#home"
end

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :permalink %><br />
    <%= f.text_field :permalink %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/createcharts.html.erb
<table>
  <tr>
    <%= session[:xaxis1] %>
    <td style="padding-right:20px;"><p>Tables</p>
      <% @alltables.each do |table| %>
        <%= link_to table, table1_page_path(table.to_s), :method => :put %><br/>
      <% end %></td>
    <td valign="top">
      <% if session[:table1]%>
        <% if session[:xaxis1] %>
          <p>Please choose y axis from table <%= session[:table1] %>:</p>
        <% else %>
          <p>Please choose x axis from table
            <% if session[:table1] %>
              <%= session[:table2] %>:
            <% else %>
              <%= session[:table1] %>:
            <% end %>
          </p>
        <% end %>
        <% @ds2[0].keys.each do |k|  %>
          <% if session[:xaxis1] %>
            <%= link_to k, yaxis1_page_path(k.to_s), :method => :put %><br/>
          <% else %>
            <%= link_to k, xaxis1_page_path(k.to_s), :method => :put %><br/>
          <% end %>
        <% end %>
      <% end %>
    </td>
  </tr>
</table>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/home.html.erb
			<div class="banner">
				<p><span class="blue">Gives businesses</span> <span class="light-blue">access</span> 
				to enterprise level analytics tools that they need to rock their databases in realtime.
				<a href="/users/sign_in" class="strat-now">Start Now Free</a></p>

				<img src="/images/apple.png" alt="" width="436" height="253" />
			</div>
			<div class="additional-links">
				<a href="#" class="doc">Documentation</a>
				<a href="#" class="plans">Pricing Plans</a>
				<a href="#" class="blog">Our Blog</a>
			</div>

			<div class="info">
				<h1 class="title"><span>Easy, Breezy</span> Dashboard Creation</h1>
				<div class="text-line">
					<p class="left-side"><span>The easiest business dashboard you've ever used. Don't waste time and money by building your own.</span>Tired of waiting for IT to run the reports you need? Don't want to spend forever learning SQL? Fed up with dumping results to Excel? Chart.io lets you interact with your database data intuitively via drag and drop.</p>
					<img src="/images/content-img01.jpg" alt="" width="466" height="166" class="right-side" />
				</div>

				<div class="text-line">
					<img src="/images/content-img02.jpg" alt="" width="465" height="236" class="left-side" />
					<p class="right-side"><span>The moment you sign up, we automatically create a rich dashboard of your key business metrics.</span>After you've connected your database to DreamDash, we analyze its schema and generate a variety of analyses and charts we think will be valuable to your business.<br />DreamDash starts you with a working dashboard and lets you add to it easily.</p>
				</div>
				<a href="#" class="full-doc">View Full Documentation</a>
			</div>
			<div class="partners">

				<a href="#" class="airbnb"></a>
				<a href="#" class="dreamhost"></a>
				<a href="#" class="citypocket"></a>
				<a href="#" class="speakertext"></a>
				<a href="#" class="toutapp"></a>
			</div>

app/views/pages/index.html.erb
<% content_for :head do %>
		<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
		<script type="text/javascript" src="/javascripts/highcharts.js"></script>
		<% if params[:table]%>
		<script type="text/javascript">
		
			var chart;
			$(document).ready(function() {
				chart = new Highcharts.Chart({
					chart: {
						renderTo: 'container',
						defaultSeriesType: 'line'
					},
					title: {
						text: 'Created records'
					},
					xAxis: {
						categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
					},
					yAxis: {
						title: {
							text: 'Created'
						}
					},
					tooltip: {
						enabled: false,
						formatter: function() {
							return '<b>'+ this.series.name +'</b><br/>'+
								this.x +': '+ this.y +'°C';
						}
					},
					plotOptions: {
						line: {
							dataLabels: {
								enabled: true
							},
							enableMouseTracking: false
						}
					},
					series: [ {
						name: '<%= params[:table] %>',
						data: [<%= @jan.count %>, <%= @feb.count %>, <%= @mar.count %>, <%= @apr.count %>, <%= @may.count %>, 
						<%= @jun.count %>, <%= @jul.count %>, <%= @avg.count %>, <%= @sep.count %>, <%= @okt.count %>, 
						<%= @nov.count %>, <%= @dec.count %>]
					}]
				});
				
				
			});
				
		</script>
		<% end %>
	
<% end %>
<table>
	<tr>
		<td><% @alltables.each do |row| %>
		<%= link_to row, pages_path + "?table=" + row.to_s %><br/>
		<% end %></td>
		<td><div id="container" style="width: 800px; height: 400px; margin: 0 auto"></div></td>
	</tr>
</table>

app/views/pages/layers.html.erb
		<% require 'sequel' %>
<% content_for :head do %>
		<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
		<script type="text/javascript" src="/javascripts/highcharts.js"></script>
		<script type="text/javascript" src="/javascripts/modules/exporting.js"></script>
		
<script type="text/javascript">

		var chart;
		jQuery(document).ready(function() {
			chart = new Highcharts.Chart({
				chart: {
					renderTo: 'container',
					defaultSeriesType: 'line'
				},
				title: {
					text: 'Layers and Filters',
					x: -20 //center
				},
				xAxis: {
categories: [
						"afton.hudson@ritchie.biz", 
						"davon@collins.name", 
						"treva@wisokymaggio.biz", 
						"madonna@tremblaystroman.org", 
						"tomasa_gusikowski@kohler.biz", 
						"sammie@heaney.net", 
						"ezequiel_bruen@marvin.info", 
						"alexie.gusikowski@glover.info", 
						"evie@schiller.biz", 
						"zack_lindgren@brekke.org", 
						"roel@schoen.org", 
						"maci@volkmanfeil.name", 
						"easter@konopelski.com", 
						"cora@tromp.com", 
						"daren@nolan.org", 
						"furman_feil@predovic.net", 
						"alexander@swaniawski.name", 
						"briana.johnston@west.net", 
						"kim.auer@abernathyjohns.info", 
						"darien@beier.info", 
						"stevie_dicki@brakusohara.net", 
						"coby@skiles.net", 
						"samson@beermayer.net", 
						"stevie@hirthe.biz", 
						"dale.streich@deckow.name", 
						"ardella@fadelconnelly.com", 
						"lucio.kertzmann@crooks.biz", 
						"stephon_mckenzie@rempel.name", 
						"janae@effertzkulas.info", 
						"jaron@baumbach.com", 
						"tomasa_mann@schadencummings.name", 
						"dorcas.konopelski@quigleyauer.biz", 
						"kelvin.greenholt@hellerleffler.biz", 
						"natalie.parker@nolan.org", 
						"sadye@wiza.biz", 
						"kelvin@eichmann.org", 
						"carlee.skiles@fadelhoppe.name", 
						"claudia@rice.net", 
						"eliezer.jacobson@mann.biz", 
						"rahsaan@rosenbaumkemmer.name", 
						"anastacio@keeblergibson.info", 
						"letha@tillman.com", 
						"christian@pfannerstill.info", 
						"baron.hamill@armstronghowe.org", 
						"miracle.kirlin@parkerhuels.name", 
						"edison@kozeybergstrom.com", 
						"janice_hickle@wisozk.name", 
						"malachi@hessel.info", 
						"abigale@murazik.biz", 
						"keara.bailey@okon.com", 
						"mallory_batz@hessellangosh.org", 
						"ivah@braunlittel.com", 
						"vicenta_larson@kilbacktowne.net", 
						"orval_jakubowski@hilpertparker.com", 
						"nedra@howe.info", 
						"dane_reichel@schneiderstreich.name", 
						"hailee@raynorstark.info", 
						"kayli@ortiz.net", 
						"reid_west@kuphal.name", 
						"kelsie@danielupton.org", 
						"julius_rohan@denesiklittel.name", 
						"jammie_heidenreich@toykautzer.net", 
						"makenzie@kesslereffertz.name", 
						"jasper@little.com", 
						"jacynthe@altenwerth.biz", 
						"aglae@herman.net", 
						"ramiro@miller.org", 
						"isabell_gislason@veumschmitt.info", 
						"avery.nolan@batzkemmer.name", 
						"deontae.lueilwitz@stehr.com", 
						"jazmin@murray.name", 
						"norval.schuppe@heaney.org", 
						"ivory.sauer@konopelski.net", 
						"kellen@hirthe.net", 
						"leopoldo_gusikowski@streich.info", 
						"camille@okuneva.info", 
						"princess.wintheiser@considinewalter.org", 
						"nash_cormier@lehnergoodwin.org", 
						"brendon@bayer.net", 
						"maia_haag@langworth.com", 
						"mavis.kunde@sauer.net", 
						"winfield@ankunding.org", 
						"pat.steuber@bechtelar.name", 
						"mario@franecki.org", 
						"dangelo.homenick@hayesdeckow.name", 
						"paul@hamill.biz", 
						"emmitt.ernser@gusikowski.com", 
						"damon_wiza@krajcik.net", 
						"delia.robel@sauermurazik.biz", 
						"kacey_turcotte@watsicakassulke.org", 
						"colt.bahringer@cruickshank.org", 
						"jamar@kutchauer.net", 
						"reta@west.org", 
						"katlynn_nolan@sawayn.info", 
						"jailyn.rau@thiel.net", 
						"kayley.bashirian@hand.name", 
						"constantin_kihn@langworthschumm.com", 
						"kara_ullrich@oconner.com", 
						"linda@lefflerbernhard.name", 
						"burnice@jacobslindgren.biz", 
						"info@gtgroup.rs", 
						"info@gtgroup.rs", 
						"info@gtgroup.rs", 
						"info@gtgroup.rs", 
						"", 
						"", 
						"info@gtgroup.rs", 
						"info@gtgroup.rs", 
						]

				},
				yAxis: {
					title: {
						text: 'Values from DB'
					},
					plotLines: [{
						value: 0,
						width: 1,
						color: '#808080'
					}]
				},
				tooltip: {
					formatter: function() {
			                return '<b>'+ this.series.name +'</b><br/>'+
							this.x +': '+ this.y;
					}
				},
				series: [{
						name: "First layer",
						data: [
						<% @layer1.each do |r| %>
						<%= r[:user_id] %>, 
						<% end %>
						]

				}, {
						name: "Second layer",
						data: [
						<% @layer1.each do |r| %>
						<% if r[:id].to_i >= 467107162 %>
						<%= r[:id] %>,
						<% end %> 
						<% end %>
						]

				}, {
						name: "Third layer",
						data: [
						<% @layer1.each do |r| %>
						<%= r[:id] %>, 
						<% end %>
						]

				}, {
						name: "Four layer",
						data: [
						1303792871, 
						1303605671, 
						1304037671, 
						1302943271, 
						1303162871, 
						1303231271, 
						1303317671, 
						1304498471, 
						1302802871, 
						1303029671, 
						1303270871, 
						1303371671, 
						1303731671, 
						1303515671, 
						1303897271, 
						1304131271, 
						1304390471, 
						1303173671, 
						1303015271, 
						1304322071, 
						1304577671, 
						1303476071, 
						1304005271, 
						1304221271, 
						1303915271, 
						1304109671, 
						1303292471, 
						1304606471, 
						1304466071, 
						1304368871, 
						1304520071, 
						1302781271, 
						1304005271, 
						1304199671, 
						1303666871, 
						1303839671, 
						1303792871, 
						1303584071, 
						1302979271, 
						1303054871, 
						1303173671, 
						1303360871, 
						1302907271, 
						1303018871, 
						1303242071, 
						1303461671, 
						1304289671, 
						1303738871, 
						1303504871, 
						1302730871, 
						1303684871, 
						1304016071, 
						1304185271, 
						1302756071, 
						1304354471, 
						1304520071, 
						1304617271, 
						1304437271, 
						1303274471, 
						1303933271, 
						1304088071, 
						1303771271, 
						1303504871, 
						1304260871, 
						1302874871, 
						1303026071, 
						1303256471, 
						1303432871, 
						1302954071, 
						1303090871, 
						1303191671, 
						1303328471, 
						1303832471, 
						1303576871, 
						1303872071, 
						1303706471, 
						1303544471, 
						1302835271, 
						1303029671, 
						1303263671, 
						1303400471, 
						1304469671, 
						1302946871, 
						1303130471, 
						1303195271, 
						1303328471, 
						1304059271, 
						1303789271, 
						1303645271, 
						1303972871, 
						1304257271, 
						1303497671, 
						1304347271, 
						1304545271, 
						1302993671, 
						1303173671, 
						1304631671, 
						1304408471, 
						1303890071, 
						1304160071, 
						1304664538, 
						1306662613, 
						1307076467, 
						1307545926, 
						1307560176, 
						1308688366, 
						1308739320, 
						1308752356, 
						]

				}]
			});
			
			
		});
	</script>

	
<% end %>
<div class="left-side-charts" id="container" style="width: 420px; height: 240px; margin: 0 auto"></div>
<div class="clear"></div>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<h1 class="title"><span><%= @page.title%></span></h1>
<% if @page.documentation %>
<div class="left-side-main">
<% @documentations.each do |doc| %>
<%= link_to doc.title, "/pages/" + doc.permalink %><br/>
<% end %>
</div>
<% end %>

<% if @page.documentation %>
<div class="right-side-main">
<% end %>
<%=raw @page.body %>
<% if @page.documentation %>
</div>
<div class="clear"></div>
<% end %>

app/views/pages/test.html.erb
<% content_for :head do %>
		<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
		<script type="text/javascript" src="/javascripts/highcharts.js"></script>
		<% @charts.each_with_index do |chart, i| %>
		<script type="text/javascript">
		
			var chart;
			$(document).ready(function() {
				chart = new Highcharts.Chart({
					chart: {
						renderTo: "<%= 'container' + chart.id.to_s %>",
						defaultSeriesType: 'line'
					},
					title: {
						text: "Chart " + <%= i + 1 %>
					},
					xAxis: {
						categories: [
						<% @ds1f.each do |r| %>
						<% xic = chart.x_axis %>
						"<%= r["#{xic}".to_sym] %>", 
						<% end %>
						]
					},
					yAxis: {
						title: {
							text: "<%= "#{chart.x_axis}".to_s %>"
						}
					},
					tooltip: {
						formatter: function() {
				                return '<b>'+ this.series.name +'</b><br/>'+
								'X: ' + this.x + '<br/> Y: '+ this.y;
						}
					},

					series: [ {
						name: "<%= "#{chart.y_axis}".to_s %>",
						data: [
						<% @ds2f.each do |r| %>
						<% yic = chart.y_axis %>
						<%= r["#{yic}".to_sym].to_i %>, 
						<% end %>
						]
					}]
				});
				
				
			});
				
		</script>
		<% end %>
	
<% end %>
<% @charts.each do |chart| %>
<div class="left-side-charts" id="<%= 'container' + chart.id.to_s %>" style="width: 510px; height: 290px; margin: 0 auto"></div>
<% end %>
<div class="clear"></div>