config/routes.rb
Dreamdash::Application.routes.draw do
  resources :dashboards do
  	put :change, :on => :member
  end
  
  resources :charts do
    collection do
      get :test_draggable
    end
  end
  
  resources :datasources
  

  resources :pages do
  	put :table1, :on => :member
  	put :xaxis1, :on => :member
  	put :yaxis1, :on => :member
  end
  
  devise_for :users

  match "dashboard" => "pages#test"
  match "layers" => "pages#layers"  
  match "new_chart" => "pages#createcharts"

  root :to => "pages#home"
end

app/views/layouts/admin.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <%= csrf_meta_tag %>
    <!--[if IE 7]>
		<style type="text/css">
			.header_resize ul.dropdown ul { top:59px; }
		</style>
	<![endif]-->
    <%= javascript_include_tag 'jquery' %>
    <%= javascript_include_tag 'jquery-ui' %>
    <%= javascript_include_tag 'jquery_ujs' %>
    <%= javascript_include_tag 'application' %>
    <%= stylesheet_link_tag 'jquery-ui-1.8.17.custom' %>
    <%= stylesheet_link_tag 'buttons' %>
    <%= stylesheet_link_tag 'admin' %>
    <%= yield :head -%>
    <title>DreamDash Admin Panel</title>

  </head>
  <body>
    <!-- __________________________________________________________________ header __________________________________________________________________ -->
    <div class="header">
      <div class="clouds"></div>
      <div class="header_resize">
        <h1 class="logo"><a href="index.html"></a></h1>
        <ul class="dropdown">
          <li>Test Project for Me
            <ul class="sub-menu">
              <li><a href="#">Sub Menu</a></li>

              <li><a href="#">Sub Menu</a></li>
              <li><a href="#">Sub Menu</a></li>
              <li><a href="#">Sub Menu</a></li>
            </ul>
          </li>
        </ul>
        <ul class="admin-menu">

          <li><a href="/dashboards"><span class="menu-1"></span>Dashboards</a></li>
          <li><a href="#"><span class="menu-2"></span>Settings</a></li>
          <li><a href="#"><span class="menu-3"></span>Help</a></li>
          <% if current_user %>
            <li><a href="/users/sign_out" data-method="delete" rel="nofollow"><span class="menu-4"></span>Signout</a></li>
          <% end %>

        </ul>
      </div>
    </div>

    <!-- __________________________________________________________________ content __________________________________________________________________ -->
    <div class="content">
      <div class="content_resize">
        <%- if @hide_dashboard_menu.nil? %>
          <div class="dashboard-menu">
            <p class="left-side">Select a Dashboard</p>
            <% @dashboards = Dashboard.find(:all, :conditions => ["user_id = ?", current_user.id]) %>
            <% @dashboards.each do |d| %>
              <%= button_to d.title, change_dashboard_path(d), :method => :put, :class => "left-side main"%>
            <% end %>
            <%= link_to "", "/dashboards/new", :class => "left-side plus" %>
            <%= link_to "Create new Chart", "/charts/new", :class => "right-side new-chart"%>
            <a href="#" class="right-side arrange-mode"><span id="off-on">off</span>Arrange Mode</a>
          </div>
        <% end %>

        <%= yield %>
        <div style="height:20px;"></div>
      </div>
    </div>
    <!-- __________________________________________________________________ footer __________________________________________________________________ -->
    <div class="footer">
      <div class="footer_resize">
        <ul>
          <li><%= link_to "home", "/pages/home"%></li>
          <li><%= link_to "about", "/pages/about-us"%></li>
          <li><%= link_to "pricing", "/pages/pricing"%></li>
          <li><a href="#">documentation</a></li>
          <li><a href="#">blog</a></li>
          <li><a href="#">contact us</a></li>
        </ul>
        <p>Copyright &#169; 2011 DreamDash</p>

      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<link href="/stylesheets/main.css" rel="stylesheet" type="text/css" />	
    <%= javascript_include_tag :defaults %>
    <%= yield :head -%>
    <%= csrf_meta_tag %>		
	<title>DreamDash Home Page</title>
</head>
<body>
<!-- __________header___________ -->
	<div class="header">
		<div class="top-clouds"></div>
		<div class="header_resize">
		<% if current_user %>
		<%= link_to "Logout", destroy_user_session_path, :method => :delete, :class => "login" %>
		<% else %>
		<%= link_to "Login", new_user_session_path, :class => "login" %>
		<% end %>

			<h1 class="logo"><a href="/"></a></h1>
			<div class="site-nav">
				<div class="left-side-bg"></div>
				<ul>
					<li><%= link_to "about us", "/pages/about-us"%></li>
					<li><%= link_to "pricing", "/pages/pricing"%></li>
					<li><%= link_to "documentation", "/pages/documentation"%></li>

					<li><a href="#">blog</a></li>
					<li class="last"><%= link_to "contact", "/pages/contact-us"%></li>
				</ul>
				<div class="right-side-bg"></div>
			</div>
			<h1 class="slogan">Google Analytics for Business Data</h1>
		</div>

		<div class="bottom-clouds"></div>
	</div>
<!-- ________content __________ -->
<div class="content">
	<div style="height:70px;"></div>
    <%= yield %>
    <div style="height:20px;"></div>
</div>
<!-- _____footer _____-->
	<div class="footer">

		<div class="footer_resize">
			<ul>
				<li><%= link_to "home", "/pages/home"%></li>
				<li><%= link_to "about", "/pages/about-us"%></li>
				<li><%= link_to "pricing", "/pages/pricing"%></li>
				<li><a href="#">documentation</a></li>
				<li><a href="#">blog</a></li>

				<li><%= link_to "contact us", "/pages/contact-us"%></li>
			</ul>
			<p>Copyright &#169; 2011 DreamDash</p>
		</div>
	</div>
</body> 
</html>